Apply theme to curate
gliff-ai/curate pull request #112
Opened 2021-06-23 11:10 UTC by ChrisBaidoo

# Description

Apply new gliff.ai branding guide to 

closes # #101
relates # (issue)

# Dependency changes

List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or package-lock.json been updated?

# Testing

Please describe the new tests that have been added for this change.
Provide any additional instructions required to reproduce a successful test.
Please also list any relevant details for your test configuration

# Documentation

# Migrations (if applicable)

Have any database migrations been committed as part of this pull request?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-23 11:34 UTC, cooper667 commented
Could the buttons have tooltips? (I have no idea what the one on the bottom left should do)

2021-06-23 12:55 UTC, SilviaZeta commented on examples/index.html
>    </body>
Can we move this styling out of the html file, pls?

2021-06-23 13:01 UTC, SilviaZeta commented on src/components/SizeThumbnails.tsx
> +    if (buttonClicked === "Medium") {
else if?

2021-06-23 13:17 UTC, SilviaZeta commented
When I click on the select images button, then on a thumbnail, the only thing left in the left section is the delete button and I don't find a way to return to the original view.

2021-06-23 20:59 UTC, cooper667 submitted a review, later dismissed

2021-06-24 09:40 UTC, ChasNelson1990 requested changes
Looking good guys!

A few visual things from me:

- [ ] the small/medium/large icons are, on my screen a little aliased. Not sure if this screenshot shows it well enough but it looks a bit naff because of that. Can we just check we're using the SVGs?
![Screenshot_2021-06-24_10-30-24](https://user-images.githubusercontent.com/7795189/123240132-f21d5d80-d4d7-11eb-9ec4-b5eb18ac25e2.png)
- [x] What does this icon mean - didn't seem to do anything when I clicked. I think @cooper667 suggested tooltips - good suggestion, can we add them?
![Screenshot_2021-06-24_10-31-12](https://user-images.githubusercontent.com/7795189/123240225-08c3b480-d4d8-11eb-95dc-10cb4e1cd1d6.png)
- [ ] Are the Select All/Select None labels means to hover highlight in this way (not fully coloured but partly coloured)? I note that they are the only buttons to have a hover effect, shouldn't all the buttons hover the same as in ANNOTATE?
![Screenshot_2021-06-24_10-31-38](https://user-images.githubusercontent.com/7795189/123240433-37418f80-d4d8-11eb-960c-0224b37b2ba3.png)
- [ ] Have you checked this out on an iPad or even just a 50% width desktop monitor? Everything is a bit skewiff, maybe @joshuajames-smith could have a think about how to deal with these smaller screens?
![salmon-meadow-05ee3f103-112 westeurope azurestaticapps net_(iPad)](https://user-images.githubusercontent.com/7795189/123240545-4e807d00-d4d8-11eb-9241-bee74f88f788.png)

2021-06-29 09:05 UTC, cooper667 approved these changes

2021-06-29 09:34 UTC, cooper667 approved these changes

2021-06-29 09:37 UTC, SilviaZeta approved these changes

2021-06-29 09:55 UTC, philipjackson approved these changes

2021-06-29 10:30 UTC, ChasNelson1990 approved these changes

2021-06-29 10:31 UTC, merged