Autoload
gliff-ai/curate pull request #15
Opened 2021-04-27 16:11 UTC by philipjackson

# Description

Added a toy dataset of 20 RGB png images, and some code in `examples/src/index.tsx` to autoload them and pass them into `UserInterface` as props. Right now there is a simple interface for passing in tiles as an array of `{name, label, thumbnail}` objects. For now I've gone with base64 for the images, since `ImageBitmap` would require us to spawn a new canvas for every thumbnail tile which sounded a bit mad. 

There's currently no distinction between thumbnails and actual images, but I'm guessing CURATE shouldn't need the all the full images upfront anyway.

relates #1 #4

# Dependency changes

material-ui

# Testing

N/A

# Documentation

N/A

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-27 18:08 UTC, ChasNelson1990 requested changes
instead of adding these images, which aren't our images, does it make more sense to have a small script that downloads them directly from their source?

2021-04-27 18:08 UTC, ChasNelson1990 commented on src/index.tsx
> +      {props.tiles.map((tile, index) => (
Replace with (I think):
```typescript
      {props.tiles.map((tile) => (
        <Grid item xs={1} key={tile.id}>
          <img
            height={128}
            src={`data:image/png;base64,${tile.thumbnail}`}
            alt={tile.name}
          />
        </Grid>
      ))}
```

2021-04-28 08:54 UTC, philipjackson commented on src/index.tsx
> +      {props.tiles.map((tile, index) => (
Done

2021-04-28 10:43 UTC, ChasNelson1990 commented
> instead of adding these images, which aren't our images, does it make more sense to have a small script that downloads them directly from their source?

Did you think any further about this one @philipjackson ?

2021-04-28 13:50 UTC, philipjackson commented
> > instead of adding these images, which aren't our images, does it make more sense to have a small script that downloads them directly from their source?
> 
> Did you think any further about this one @philipjackson ?

I probably _could_, but the source is an 840MB zip file from BBBC. The images I've saved to the repo were created by stacking three of the images in that zip and then slicing into 20 equally sized tiles in numpy.

2021-04-28 18:45 UTC, ChasNelson1990 submitted a review, later dismissed

2021-04-30 14:04 UTC, ChasNelson1990 submitted a review, later dismissed

2021-04-30 14:24 UTC, ChasNelson1990 approved these changes

2021-05-04 08:27 UTC, cooper667 approved these changes

2021-05-04 09:02 UTC, merged