Import text base button
gliff-ai/curate pull request #181
Opened 2021-08-19 08:37 UTC by ChrisBaidoo

## Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.

closes # (issue)
relates # (issue)

## Dependency changes

List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or package-lock.json been updated?

## Testing

Please describe the new tests that have been added for this change.
Provide any additional instructions required to reproduce a successful test.
Please also list any relevant details for your test configuration

## Documentation

Please describe the new documentation that has been added for this change?
Is there new user documentation?
Is there new developer documentation?
Is the developer documentation purely generated from docstrings in the code?

## Migrations (if applicable)

Have any database migrations been committed as part of this pull request?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

2021-08-19 16:16 UTC, ChasNelson1990 requested changes
Can we use a conventional commit for the PR name (makes it easier to remember to do so for the squash merge)

2021-08-19 16:16 UTC, ChasNelson1990 commented on src/sort/SortPopover.tsx
> +              text="Sort"
Should text really be a prop and not a child?

2021-08-19 16:17 UTC, ChasNelson1990 commented on src/sort/SortPopover.tsx
> +              text="Sort"
Up for discussion but it seems odd to me?

2021-08-23 13:12 UTC, philipjackson approved these changes

2021-09-14 09:25 UTC, cooper667 submitted a review, later dismissed

2021-09-14 11:28 UTC, philipjackson approved these changes

2021-09-14 13:27 UTC, cooper667 approved these changes

2021-09-16 11:06 UTC, cooper667 approved these changes

2021-09-16 14:10 UTC, philipjackson approved these changes

2021-09-16 14:14 UTC, merged