refactor!: New plugins toolbar
gliff-ai/curate pull request #344
Opened 2022-02-11 17:26 UTC by SilviaZeta

## Description
closes gliff-ai/annotate#496

Note: link to the plugins doc is missing and lines 105-122 in `PluginsDialog` can be deleted once gliff-ai/plugin_geolocation-map#9 is merged.

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-02-17 10:35 UTC, ChasNelson1990 requested changes
1) when I first load CURATE, the plugins drawer does not exist. When I click the plugins button it appears (a bit dramatically lol) and then if I click the button again it disappears. However, if I click the drawer up arrow thingy, the drawer doesn't disappear - it just closes. Is this not a bit inconsistent? Do we actually want a button at all - maybe we just have a drawer and use the icon in the top left of the drawer (which would start closed by default)? @joshuajames-smith ?

2) When closed, the drawers have square corners instead of round.

3) see also the comment about tooltips in the ANNOTATE PR

2022-02-18 09:57 UTC, joshuajames-smith commented
> * when I first load CURATE, the plugins drawer does not exist. When I click the plugins button it appears (a bit dramatically lol) and then if I click the button again it disappears. However, if I click the drawer up arrow thingy, the drawer doesn't disappear - it just closes. Is this not a bit inconsistent? Do we actually want a button at all - maybe we just have a drawer and use the icon in the top left of the drawer (which would start closed by default)? @joshuajames-smith ?

The original UX idea was the icon acted as a toggle as a way to customise workspace for user workflow needs - they might not always need plugins active (and taking up space)? @ChasNelson1990 

I'm happy for the drawer to attached to and below `Annotation Labels` but wether open or closed, it should stay connected or disconnected - but it should be one or other ideally for a consistency!

2022-02-21 10:30 UTC, ChasNelson1990 approved these changes
Doesn't need to be fixed in this PR but for @ChrisBaidoo 's attention for when they move the Drawer component into STYLE:

1. there is a weird line above the drawer when closed:
![image](https://user-images.githubusercontent.com/7795189/154937329-2dcec30e-aef3-4bfc-91e3-4b3d146fb336.png)

2. Looks like the paper inside the drawer has square corners that overlap the round corners of the drawer, interestingly this only seems to be on hover?
![image](https://user-images.githubusercontent.com/7795189/154937437-9d250943-f2bf-4b88-934c-92d1859ef371.png)

2022-02-21 15:51 UTC, joshuajames-smith approved these changes

2022-02-21 15:51 UTC, merged