Dataset table view
gliff-ai/curate pull request #402
Opened 2022-05-23 07:01 UTC by ChrisBaidoo

## Description

Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).

Don't forget to reference all other pull requests which are associated to this one below: e.g.

closes #(issue-number)
relates gliff-ai/(repository-name)#(issue-number)

## Dependency Changes (delete if not applicable)

List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or package-lock.json been updated?

## Testing (delete if not applicable)

Please describe the new tests that have been added for this change along with any additional instructions required to reproduce a successful test and/or a list of any relevant details for your test configuration.

## Documentation (delete if not applicable)

Please describe the new documentation that has been added for this change (is there new user documentation? is there new developer documentation? is the developer documentation purely generated from docstrings in the code?).

## Database Changes (delete if not applicable)

Have any database changes been committed as part of this pull request?

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-05-26 04:39 UTC, cooper667 reviewed
To fix the build errors I _think_ we need to bump Material UI, which creates other problems...I'm going to try that in a different branch!

2022-05-26 04:39 UTC, cooper667 commented on src/components/Tooltips.ts
> +interface DatasetType {
Maybe `DatasetViewType` as the name?

2022-05-26 04:39 UTC, cooper667 commented on src/components/Tooltips.ts
> +interface DatasetType {
Also doesn't need exporting?

2022-05-26 04:39 UTC, cooper667 commented on src/ui.tsx
> +          const moreLabelsCount = imageLabels.length - 2;
```suggestion
          const moreLabelsCount = imageLabels.length - chipsLimit;
```

2022-05-26 04:39 UTC, cooper667 commented on src/ui.tsx
> +        renderCell: (params: GridRenderCellParams<any, any, any>) => {
```suggestion
renderCell: (params: GridRenderCellParams<unknown, MetaItem, unknown>) => {
```

should remove the need to ignore ES Lint below

2022-05-26 04:39 UTC, cooper667 commented on src/ui.tsx
> +          sx={{ height: "600px" }}
This needs to fill the page rather than be fixed

2022-05-26 04:40 UTC, cooper667 commented on src/ui.tsx
> +        renderCell: (params: GridRenderCellParams<any, any, any>) => {
and also you might not need to cast to `string[]` on the line below

2022-05-26 13:23 UTC, joshuajames-smith requested changes
<img width="1784" alt="Screenshot 2022-05-26 at 14 17 53" src="https://user-images.githubusercontent.com/83074763/170495839-86bdb71f-ac79-4ad1-921a-5eabf3171f12.png">

- [ ] Can the datagrid align to the bottom? Similar to how in MANAGE the tables align at the bottom!
- [ ] Can we set some rules to have space between the columns? There is two columns in staging that are next to each other and would benefit from visual space between them.
- [x] We use pagination but only have 1 arrow - assuming this is done automatically? Can we either abandoned pagination for a full scrollable list or increase number of results shown at once (maybe 60?) and add in full pagination arrows?

2022-05-27 06:17 UTC, cooper667 commented
> We use pagination but only have 1 arrow - assuming this is done automatically? Can we either abandoned pagination for a full scrollable list or increase number of results shown at once (maybe 60?) and add in full pagination arrows?

Regarding this, should we just NOT have pagination as we have always loaded the full dataset (_i think_) so it's not like we need to implement infinite scroll or anything, we have it all and the pagination is currently artificial? Then maybe add pagination in the future when we actually lazy load the data?

(one for @joshuajames-smith and/or @ChasNelson1990  and/or @ChrisBaidoo )

2022-05-27 06:18 UTC, cooper667 submitted a review, later dismissed

2022-05-27 09:26 UTC, joshuajames-smith commented
> > We use pagination but only have 1 arrow - assuming this is done automatically? Can we either abandoned pagination for a full scrollable list or increase number of results shown at once (maybe 60?) and add in full pagination arrows?
> 
> Regarding this, should we just NOT have pagination as we have always loaded the full dataset (_i think_) so it's not like we need to implement infinite scroll or anything, we have it all and the pagination is currently artificial? Then maybe add pagination in the future when we actually lazy load the data?
> 
> (one for @joshuajames-smith and/or @ChasNelson1990 and/or @ChrisBaidoo )

Last spoke to @ChasNelson1990 I believe something was mentioned how pagination is good for E2E? But from my POV im happy with full data load with scroll - this is supported by the filter/search system anyway!

2022-05-27 09:27 UTC, joshuajames-smith reviewed
@ChrisBaidoo is it possible to load all the data at once and remove pagination?

2022-05-27 10:57 UTC, cooper667 approved these changes

2022-05-27 12:14 UTC, ChasNelson1990 approved these changes
Great work, looks good to me!

2022-05-27 12:31 UTC, joshuajames-smith approved these changes

2022-05-27 13:24 UTC, merged