feat: View annotations
gliff-ai/curate pull request #403
Opened 2022-05-25 14:30 UTC by philipjackson

## Description

Adds the button / dialog for viewing annotations by other users, accessible only to team members / admins. This dialog will later be extended to allow selection of two users, to compare their annotations side-by-side.

closes #400 

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-05-26 04:58 UTC, cooper667 commented on src/components/ViewAnnotationsDialog.tsx
> +              onClick={() => {}}
Should close dialog?

2022-05-26 05:00 UTC, cooper667 commented on src/components/ViewAnnotationsDialog.tsx
> +        <CardContent>
Are these needed with our dialog component?

2022-05-26 08:19 UTC, ChasNelson1990 commented
Could we update the examples data to mock some assignees so there's a MWE of the dialog working?

2022-05-26 14:27 UTC, philipjackson commented on src/components/ViewAnnotationsDialog.tsx
> +              onClick={() => {}}
Fixed

2022-05-26 15:01 UTC, philipjackson commented
> Could we update the examples data to mock some assignees so there's a MWE of the dialog working?

I've added some assignees to the example in `metadata.json`, so you can see them in the dialog (still won't redirect in standalone of course).

2022-05-27 06:24 UTC, cooper667 approved these changes

2022-05-27 09:42 UTC, joshuajames-smith requested changes
<img width="280" alt="Screenshot 2022-05-27 at 10 29 06" src="https://user-images.githubusercontent.com/83074763/170672903-844ed84d-bc81-44f5-b3f7-e55b12363aa5.png">

Can we move the icon to below the metadata? And also replace the image with the `eye` icon to match the original design?

<img width="450" alt="Screenshot 2022-05-27 at 10 30 07" src="https://user-images.githubusercontent.com/83074763/170672908-2cd9f35c-b63c-476a-ba97-36cea395a1ea.png">

The native browser password icon/functionality appears here and it shouldn't / doesn't anywhere else but the login/signup process? Can we remove this?

<img width="450" alt="Screenshot 2022-05-27 at 10 31 08" src="https://user-images.githubusercontent.com/83074763/170672927-ed2c4c70-8b25-4fe2-9d3b-4488aa6f59a6.png">

There is a line/divider under the input field, can we remove this?

2022-05-31 11:45 UTC, joshuajames-smith requested changes
<img width="450" alt="Screenshot 2022-05-31 at 12 44 44" src="https://user-images.githubusercontent.com/83074763/171165701-516d9a49-f03c-4098-b65b-ce2e37e72340.png">

Can we use `user name` rather than `user email`? Otherwise it looks good!

2022-06-03 21:20 UTC, philipjackson commented
> Can we use `user name` rather than `user email`? Otherwise it looks good!

So I've got this working now, but just realised that names aren't necessarily unique, that's why we generally use emails as usernames. @ChasNelson1990 should we go with name names or stick to emails here?

2022-06-07 08:06 UTC, cooper667 commented
> > Can we use `user name` rather than `user email`? Otherwise it looks good!
> 
> So I've got this working now, but just realised that names aren't necessarily unique, that's why we generally use emails as usernames. @ChasNelson1990 should we go with name names or stick to emails here?

do users _have_ names?

2022-06-07 16:49 UTC, philipjackson commented
> We ask for user `name` during sign up. This is likely to be much clearer UX when selecting users via name vs emails as not _all_ emails will be nice and clear.
> 
> I wonder now if it makes sense to change the `name` field within the sign up to `first name(s)` and `last name` so we ensure full user names are collected to be used by the platform?

So I had a look at how we currently handle this in MANAGE, seems we actually use both there, so I've done the same here for now :)

![image](https://user-images.githubusercontent.com/26219665/172438339-835dd774-e342-49be-a6ed-cafdeec74d82.png)

2022-06-08 02:29 UTC, cooper667 commented
>I wonder now if it makes sense to change the name field within the sign up to first name(s) and last name so we ensure full user names are collected to be used by the platform?

i don't want to do that migration 😀 


>So I had a look at how we currently handle this in MANAGE, seems we actually use both there, so I've done the same here for now :)

exactly what i was about to suggest

2022-06-08 02:30 UTC, cooper667 submitted a review, later dismissed

2022-06-08 08:30 UTC, ChasNelson1990 submitted a review, later dismissed

2022-06-08 09:39 UTC, joshuajames-smith requested changes
<img width="460" alt="Screenshot 2022-06-08 at 10 27 39" src="https://user-images.githubusercontent.com/83074763/172582757-0d674962-7df2-4d6b-a4d1-69a70b87507a.png">

^ I've noticed that the select field is automatically filled? I think we want to avoid this so users are required to select a user themselves. Can we ensure this select field is left empty to begin with?

<img width="460" alt="Screenshot 2022-06-08 at 10 28 04" src="https://user-images.githubusercontent.com/83074763/172583154-cd656651-8560-4ede-aea8-b456fb04dd7e.png">

^ There is also another issue. If I select a user to view annotations on a first image and then cancel and select a second image to view annotations, the user appears the same. In the case above, that user is NOT assigned to that image so they shouldn't show anyway? I think the above fix would solve this anyways!

2022-06-13 10:09 UTC, philipjackson commented
> ^ There is also another issue. If I select a user to view annotations on a first image and then cancel and select a second image to view annotations, the user appears the same. In the case above, that user is NOT assigned to that image so they shouldn't show anyway? I think the above fix would solve this anyways!

Good catch, it definitely wasn't supposed to do that. Fixed now :+1:

2022-06-13 11:44 UTC, ChasNelson1990 submitted a review, later dismissed

2022-06-13 11:57 UTC, joshuajames-smith submitted a review, later dismissed

2022-06-13 14:51 UTC, cooper667 submitted a review, later dismissed

2022-06-13 14:59 UTC, joshuajames-smith approved these changes

2022-06-13 15:43 UTC, SilviaZeta approved these changes

2022-06-13 15:43 UTC, merged